{% set version = '0.8.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-baizer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/baizer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/baizer/baizer_{{ version }}.tar.gz
  sha256: 2ab9c74ba501cd4b44ece378d166eef41ada831e43bac1ec169eb07fc379c719

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-curl
    - r-diffobj
    - r-dplyr >=1.1.0
    - r-magrittr
    - r-openxlsx
    - r-purrr
    - r-readr
    - r-readxl
    - r-rematch2
    - r-rlang >=0.4.11
    - r-rmarkdown
    - r-seriation
    - r-stringr
    - r-tibble >=3.1
    - r-tidyr
    - r-vctrs
  run:
    - r-base
    - r-curl
    - r-diffobj
    - r-dplyr >=1.1.0
    - r-magrittr
    - r-openxlsx
    - r-purrr
    - r-readr
    - r-readxl
    - r-rematch2
    - r-rlang >=0.4.11
    - r-rmarkdown
    - r-seriation
    - r-stringr
    - r-tibble >=3.1
    - r-tidyr
    - r-vctrs

test:
  commands:
    - $R -e "library('baizer')"           # [not win]
    - "\"%R%\" -e \"library('baizer')\""  # [win]

about:
  home: https://william-swl.github.io/baizer/, https://github.com/william-swl/baizer
  license: MIT
  summary: In ancient Chinese mythology, Bai Ze is a divine creature that knows the needs of
    everything. 'baizer' provides data processing functions frequently used by the author.
    Hope this package also knows what you want!
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: baizer
# Title: Useful Functions for Data Processing
# Version: 0.8.0
# Authors@R: person("William", "Song", , "william_swl@163.com", role = c("aut", "cre"))
# Description: In ancient Chinese mythology, Bai Ze is a divine creature that knows the needs of everything. 'baizer' provides data processing functions frequently used by the author. Hope this package also knows what you want!
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Imports: curl, diffobj, dplyr (>= 1.1.0), grDevices, magrittr, methods, openxlsx, purrr, readr, readxl, rematch2, rlang (>= 0.4.11), rmarkdown, seriation, stats, stringr, tibble (>= 3.1), tidyr, utils, vctrs
# Suggests: covr, roxygen2, testthat (>= 3.0.0), withr
# Config/testthat/edition: 3
# Depends: R (>= 3.5.0)
# LazyData: true
# URL: https://william-swl.github.io/baizer/, https://github.com/william-swl/baizer
# BugReports: https://github.com/william-swl/baizer/issues
# NeedsCompilation: no
# Packaged: 2023-10-19 08:31:45 UTC; william
# Author: William Song [aut, cre]
# Maintainer: William Song <william_swl@163.com>
# Repository: CRAN
# Date/Publication: 2023-10-19 09:00:02 UTC
